version: '3.2'
services:
  cold:
    image: ortussolutions/commandbox
    container_name: 'coldfusion_server_commandbox'
    environment:
      - APP_DIR=/www/gvsu
      - BOX_SERVER_PROFILE=development
      - BOX_SERVER_APP_CFENGINE=adobe@2018.0.15+330106
      - CFCONFIG_ADMINPASSWORD=password
    ports:
      - "8080:8080"
    volumes:
      - ../webroot/gvsu:/www/gvsu/:cached
      - coldfusion:/usr/local/lib/serverHome/WEB-INF
  apache:
    image: httpd:latest
    container_name: apache-for-coldfusion
    ports:
      - '80:80'
    volumes:
      - ../webroot/gvsu:/www/gvsu/:cached
      - ./assets/conf:/usr/local/apache2/conf
volumes:
  coldfusion: {external: true}